apiVersion: skaffold/v1
kind: Config
metadata:
  name: timelord
deploy:
  kubectl:
    manifests:
    - k8s/timelord.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: harbor.cyverse.org/de/timelord
  local: {}
