apiVersion: apps/v1
kind: Deployment
metadata:
  name: timelord
spec:
  replicas: 2
  selector:
    matchLabels:
      de-app: timelord
  template:
    metadata:
      labels:
        de-app: timelord
        app: de
    spec:
      serviceAccountName: app-exposer
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: de-app
                operator: In
                values:
                - timelord
            topologyKey: kubernetes.io/hostname
      restartPolicy: Always
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: timezone
          configMap:
            name: timezone
            items:
              - key: timezone
                path: timezone
        - name: service-configs
          secret:
            secretName: service-configs
            items:
              - key: jobservices.yml
                path: jobservices.yml
      containers:
      - name: timelord
        image: harbor.cyverse.org/de/timelord
        env:
          - name: CLUSTER
            value: "1"
          - name: OTEL_TRACES_EXPORTER
            valueFrom:
              secretKeyRef:
                name: configs
                key: OTEL_TRACES_EXPORTER
          - name: OTEL_EXPORTER_JAEGER_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: configs
                key: OTEL_EXPORTER_JAEGER_HTTP_ENDPOINT
        volumeMounts:
          - name: localtime
            mountPath: /etc/localtime
            readOnly: true
          - name: timezone
            mountPath: /etc/timezone
            subPath: timezone
          - name: service-configs
            mountPath: /etc/iplant/de
            readOnly: true
        resources:
          requests:
            cpu: "1m"
            memory: "128Mi"
            ephemeral-storage: "1Gi"
          limits:
            cpu: "100m"
            memory: "256Mi"
            ephemeral-storage: "1Gi"
        ports:
          - name: listen-port
            containerPort: 60000
        livenessProbe:
          httpGet:
            path: /debug/vars
            port: 60000
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /debug/vars
            port: 60000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: timelord
spec:
  selector:
    de-app: timelord
  ports:
    - protocol: TCP
      port: 80
      targetPort: listen-port
